services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_tasks_auth
    ports:
      - "5432:5432"
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env.development

  mailer:
    image: mailtutan/mailtutan:latest
    container_name: mail_tutan_tasks_auth
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - mailer

volumes:
  postgresDB:

networks:
  mailer:
